#!/usr/bin/env bash
set -Eeu
set -o posix
set -o pipefail

declare -r bitcoin_target_dir="/opt/bitcoin"
declare -r coin_log="/vagrant/guest_logs/bitcoin.log"

declare -r exe_name="$0"
echo_log() {
    local log_target="$coin_log"
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $exe_name: $@" >> $log_target
}

function error
{
    echo "$1" 1>&2
    exit 1
}

function coin_install {
    set -x
    echo_log "prepping bitcoin stuff"
    sudo -u vagrant mkdir -p /home/vagrant/.bitcoin
    sudo -u vagrant cp /vagrant/conf/bitcoin.conf /home/vagrant/.bitcoin/.
    mkdir "$bitcoin_target_dir"
    cp /vagrant/ThirdParty/bitcoin_bin/bitcoind "$bitcoin_target_dir/bitcoind"
    cp /vagrant/ThirdParty/bitcoin_bin/bitcoin-cli "$bitcoin_target_dir/bitcoin-cli"
    cp /vagrant/ThirdParty/bitcoin_bin/bitcoin-tx "$bitcoin_target_dir/bitcoin-tx"
    chown -R vagrant:vagrant "$bitcoin_target_dir"
    chmod 755 "$bitcoin_target_dir/bitcoind"
    chmod 755 "$bitcoin_target_dir/bitcoin-cli"
    chmod 755 "$bitcoin_target_dir/bitcoin-tx"
}

function coin_start {
    set -x
    echo_log "starting bitcoind"
    sudo -H -u vagrant "$bitcoin_target_dir/bitcoind" #note the -H... important
    echo "Sleeping a while to let bitcoind get going..."
    sleep 5
}

function coin_stop {
    echo_log "stopping bitcoind"
    pkill -9 bitcoind
}

function coin_status {
    echo "bitcoind progress: $(tail /home/vagrant/.bitcoin/testnet3/debug.log || true)"
}

function coin_backup {
    error "coin_backup not yet implemented"
}

function coin_restore {
    error "coin_restore not yet implemented"
}

function coin_abe_start {
    error "coin_abe_start not yet implemented"
}

function coin_abe_stop {
    error "coin_abe_stop not yet implemented"
}

if [ -z "$1" ]
  then
    error "No argument supplied"
fi

case "$1" in
  "install") coin_install ;;
  "start") coin_start ;;
  "stop") coin_stop ;;
  "status") coin_status ;;
  "backup") coin_backup ;;
  "restore") coin_restore ;;
  "abe_start") coin_abe_start ;;
  "abe_stop") coin_abe_stop ;;
  *) error "Unexpected function" ;;
esac
