#!/usr/bin/python
"""
A small tool to quickly check chain synch progress. Sample output:
  {'chains': {'bitcoin_testnet': {'progress': 0.19391,
                                  'timestamp': '2012-12-23 08:48:27'},
              'dogecoin_testnet': {'progress': 0.007408,
                                   'timestamp': '2014-02-24 18:40:38'},
              'florincoin': {'progress': 0.013993,
                             'timestamp': '2013-07-06 09:28:39'},
              'litecoin_testnet': {'progress': 0.175718,
                                   'timestamp': '2013-08-17 05:45:45'}},
   'timestamp': 'Thu Jun 25 05:29:30 2015'}
"""

import pprint
import re
import time

# It would be nice to get this list from a shared config file or global environment variable. For now
# they'll just be hardcoded here
chain_nodes = [{'name':'bitcoin_testnet', 'debug_log':'/home/vagrant/.bitcoin/testnet3/debug.log'},
               {'name':'dogecoin_testnet', 'debug_log':'/home/vagrant/.dogecoin/testnet3/debug.log'},
               {'name':'litecoin_testnet', 'debug_log':'/home/vagrant/.litecoin/testnet3/debug.log'},
               {'name':'florincoin', 'debug_log':'/home/vagrant/.florincoin/debug.log'}]

current_progress = {'timestamp': time.asctime(),
                    'chains': {}}

for chain_node in chain_nodes:
    status = {'progress': None, 'timestamp': None}
    try:
        with open(chain_node['debug_log'], 'r') as debug_fd:
            # seek to last 8K of file, since the logs can get quite big
            debug_fd.seek (0, 2)
            fsize = debug_fd.tell()
            debug_fd.seek(max(fsize-8192, 0), 0)
            lines = debug_fd.readlines()
        for line in reversed(lines):
            if 'progress=' in line:
                match_progress = re.search("progress=([0-9,\.]+)", line)
                match_time = re.search("date=[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}", line)
                if match_progress:
                    status['progress'] = float(match_progress.group(0).split("=")[1])
                if match_time:
                    status['timestamp'] = match_time.group(0).split("=")[1]
                break
    finally:
        current_progress['chains'][chain_node['name']] = status

pprint.pprint(current_progress)
