#!/usr/bin/env bash
set -Eeu
set -o posix
set -o pipefail

declare -r dogecoin_target_dir="/opt/dogecoin"
declare -r coin_log="/vagrant/guest_logs/dogecoin.log"

declare -r exe_name="$0"
echo_log() {
    local log_target="$coin_log"
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $exe_name: $@" >> $log_target
}

function error {
    echo "$1" 1>&2
    exit 1
}

function coin_install {
    echo_log "prepping dogecoin stuff"
    sudo -u vagrant mkdir -p /home/vagrant/.dogecoin
    sudo -u vagrant cp /vagrant/conf/dogecoin.conf /home/vagrant/.dogecoin/.
    mkdir "$dogecoin_target_dir"
    cp /vagrant/ThirdParty/dogecoin_bin/dogecoind-1.8.2-linux64 "$dogecoin_target_dir/dogecoind"
    cp /vagrant/ThirdParty/dogecoin_bin/dogecoin-cli-1.8.2-linux64 "$dogecoin_target_dir/dogecoin-cli"
    chown -R vagrant:vagrant "$dogecoin_target_dir"
    chmod 755 "$dogecoin_target_dir/dogecoind"
    chmod 755 "$dogecoin_target_dir/dogecoin-cli"
}

function coin_start {
    echo_log "starting dogecoind"
    sudo -H -u vagrant "$dogecoin_target_dir/dogecoind" #note the -H... important
    echo "Sleeping a while to let dogecoind get going..."
    sleep 5
}

function coin_stop {
    echo_log "stopping dogecoind"
    pkill -9 dogecoind
}

function coin_status {
    echo "dogecoind progress: $(tail /home/vagrant/.dogecoin/testnet3/debug.log || true)"
}

function coin_backup {
    error "coin_backup not yet implemented"
}

function coin_restore {
    error "coin_restore not yet implemented"
}

function coin_abe_start {
    error "coin_abe_start not yet implemented"
}

function coin_abe_stop {
    error "coin_abe_stop not yet implemented"
}

if [ -z "$1" ]; then
    error "No argument supplied"
fi

case "$1" in
  "install") coin_install ;;
  "start") coin_start ;;
  "stop") coin_stop ;;
  "status") coin_status ;;
  "backup") coin_backup ;;
  "restore") coin_restore ;;
  "abe_start") coin_abe_start ;;
  "abe_stop") coin_abe_stop ;;
  *) error "Unexpected function" ;;
esac
