#!/usr/bin/env bash
set -Eeu
set -o posix
set -o pipefail

declare -r litecoin_target_dir="/opt/litecoin"
declare -r coin_log="/vagrant/guest_logs/litecoin.log"

declare -r exe_name="$0"
echo_log() {
    local log_target="$coin_log"
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $exe_name: $@" >> $log_target
}

function error
{
    echo "$1" 1>&2
    exit 1
}

function coin_install {
    set -x
    echo_log "prepping litecoin stuff"
    sudo -u vagrant mkdir -p /home/vagrant/.litecoin
    sudo -u vagrant cp /vagrant/conf/litecoin.conf /home/vagrant/.litecoin/.
    mkdir "$litecoin_target_dir"
    cp /vagrant/ThirdParty/litecoin_bin/litecoind-0.8.7.5-linux64 "$litecoin_target_dir/litecoind"
    chown -R vagrant:vagrant "$litecoin_target_dir"
    chmod 755 "$litecoin_target_dir/litecoind"
    echo "Getting ltc-scrypt Python module for abe to work with Litecoin"
    pip install ltc-scrypt

}

function coin_start {
    set -x
    echo_log "starting litecoind"
    sudo -H -u vagrant "$litecoin_target_dir/litecoind" #note the -H... important
    echo "Sleeping a while to let litecoind get going..."
    sleep 5
}

function coin_stop {
    error "coin_stop not yet implemented"
}

function coin_status {
    echo "litecoind progress: $(tail /home/vagrant/.litecoin/testnet3/debug.log || true)"
}

function coin_backup {
    error "coin_backup not yet implemented"
}

function coin_restore {
    error "coin_restore not yet implemented"
}

function coin_abe_start {
    error "coin_abe_start not yet implemented"
}

function coin_abe_stop {
    error "coin_abe_stop not yet implemented"
}

if [ -z "$1" ]
  then
    error "No argument supplied"
fi

case "$1" in
  "install") coin_install ;;
  "start") coin_start ;;
  "stop") coin_stop ;;
  "status") coin_status ;;
  "backup") coin_backup ;;
  "restore") coin_restore ;;
  "abe_start") coin_abe_start ;;
  "abe_stop") coin_abe_stop ;;
  *) error "Unexpected function" ;;
esac
